package io.elastic.jdbc;

import io.elastic.api.DynamicMetadataProvider;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import javax.json.Json;
import javax.json.JsonObject;
import javax.json.JsonObjectBuilder;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ColumnNamesForInsertProvider implements DynamicMetadataProvider {

  private static final Logger LOGGER = LoggerFactory
      .getLogger(ColumnNamesForInsertProvider.class);


  /**
   * Returns Columns list as metadata
   */

  @Override
  public JsonObject getMetaModel(JsonObject configuration) {
    String tableName = getTableName(configuration);
    Connection connection = null;
    ResultSet resultSet = null;

    JsonObjectBuilder propertiesIn = Json.createObjectBuilder();
    JsonObjectBuilder propertiesOut = Json.createObjectBuilder();
    boolean isEmpty = true;
    try {
      connection = Utils.getConnection(configuration);
      DatabaseMetaData dbMetaData = connection.getMetaData();
      final String schemaNamePattern = getSchemaNamePattern(tableName);
      final String tableNamePattern = getTableNamePattern(tableName);
      resultSet = dbMetaData.getColumns(null, schemaNamePattern, tableNamePattern, "%");
      while (resultSet.next()) {

        final boolean isRequired = isRequiredField(resultSet);
        final String fieldName = resultSet.getString("COLUMN_NAME");
        final String type = convertType(resultSet.getInt("DATA_TYPE"));
        JsonObject field = Json.createObjectBuilder()
            .add("required", isRequired)
            .add("title", fieldName)
            .add("type", type)
            .build();
        boolean isGenerated = isAutoGenerated(resultSet, configuration);
        if (!isGenerated) {
          propertiesIn.add(fieldName, field);
        }
        propertiesOut.add(fieldName, field);
        isEmpty = false;
      }
    } catch (SQLException e) {
      throw new RuntimeException(e);
    } finally {
      if (resultSet != null) {
        try {
          resultSet.close();
        } catch (SQLException e) {
          LOGGER.error("Failed to close result set", e);
        }
      }
      if (connection != null) {
        try {
          connection.close();
        } catch (SQLException e) {
          LOGGER.error("Failed to close connection", e);
        }
      }
    }
    if (isEmpty) {
      LOGGER.error("The table doesn't contain columns for inserting values");
      throw new RuntimeException("The table doesn't contain columns for inserting values");
    }
    JsonObject inMetadata = Json.createObjectBuilder()
        .add("type", "object")
        .add("properties", propertiesIn.build())
        .build();
    JsonObject outMetadata = Json.createObjectBuilder()
        .add("type", "object")
        .add("properties", propertiesOut.build())
        .build();
    return Json.createObjectBuilder()
        .add("out", outMetadata)
        .add("in", inMetadata)
        .build();
  }

  /**
   * Converts JDBC column type name to js type according to http://db.apache.org/ojb/docu/guides/jdbc-types.html
   *
   * @param sqlType JDBC column type
   */
  private String convertType(Integer sqlType) {
    if (sqlType == Types.NUMERIC || sqlType == Types.DECIMAL || sqlType == Types.TINYINT
        || sqlType == Types.SMALLINT || sqlType == Types.INTEGER || sqlType == Types.BIGINT
        || sqlType == Types.REAL || sqlType == Types.FLOAT || sqlType == Types.DOUBLE) {
      return "number";
    }
    if (sqlType == Types.BIT || sqlType == Types.BOOLEAN) {
      return "boolean";
    }
    return "string";
  }

  private String getTableName(JsonObject config) {
    final String tableName = config.getString("tableName");

    if (tableName == null || tableName.toString().isEmpty()) {
      throw new RuntimeException("Table name is required");
    }
    return tableName;
  }

  private String getTableNamePattern(String tableName) {
    if (tableName.contains(".")) {
      tableName = tableName.split("\\.")[1];
    }
    return tableName;
  }

  private String getSchemaNamePattern(String tableName) {
    String schemaName = null;
    if (tableName.contains(".")) {
      schemaName = tableName.split("\\.")[0];
    }
    return schemaName;
  }

  private Boolean isRequiredField(ResultSet resultSet) throws SQLException {
    boolean isRequired = false;
    if (resultSet.getString("IS_NULLABLE").equals("NO")) {
      if (!resultSet.getString("IS_AUTOINCREMENT").equals("YES")) {
        isRequired = true;
      }
    }
    return isRequired;
  }

  private Boolean isAutoGenerated(ResultSet resultSet, JsonObject configuration) throws SQLException {
    boolean isGenerated = false;
    boolean isMysql = configuration.getString("dbEngine").equals("mysql");
    boolean isMSSQL = configuration.getString("dbEngine").equals("mssql");
    if (isMysql){
      isGenerated = resultSet.getString("IS_GENERATEDCOLUMN").equals("YES");
    } else if (isMSSQL){
      isGenerated = resultSet.getString("SS_IS_COMPUTED").equals("1");
    }
    return isGenerated;
  }
}
