ignore:
  - package:
      name: protobuf-java
      version: 3.19.4
  - package:
      name: jackson-databind
      version: 2.14.2
  - package:
      name: guava
      version: 30.1-jre
  - vulnerability: CVE-2024-5535
    package:
      name: libssl3
      version: 3.1.5-r0
  - vulnerability: CVE-2024-5535
    package:
      name: libcrypto3
      version: 3.1.5-r0
  - vulnerability: GHSA-vmq6-5m68-f53m
    package:
      name: logback-classic
      version: 1.2.11
  - vulnerability: GHSA-vmq6-5m68-f53m
    package:
      name: logback-core
      version: 1.2.11
  - vulnerability: CVE-2023-4043
    package:
      name: parsson
      version: 1.1.2
  - vulnerability: GHSA-735f-pc8j-v9w8
    package:
      name: protobuf-java
      version: 3.25.1
  - vulnerability: CVE-2023-45853
    package:
      name: zlib
      version: 1.3.1-r2
  - vulnerability: CVE-2022-21511
    package:
      name: ojdbc8
      version: 21.5.0.0
  - vulnerability: CVE-2022-21510
    package:
      name: ojdbc8
      version: 21.5.0.0
